export const finalizado = {
  crearEvento: async (evento) => {
    throw new Error('El evento ya ha finalizado');
  },

  confirmarEvento: async (evento) => {
    throw new Error('El evento ya ha finalizado');
  },

  cancelarEvento: async (evento) => {
    throw new Error('El evento ya ha finalizado');
  },

  iniciarEvento: async (evento) => {
    throw new Error('El evento ya ha finalizado');
  },

  finalizarEvento: async (evento) => {
    throw new Error('El evento ya ha finalizado');
  },

  reprogramarEvento: async (evento) => {
    throw new Error('El evento ya ha finalizado');
  },

  continuarEvento: async (evento) => {
    throw new Error('El evento ya ha finalizado');
  }
};
